version: "2"
linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errorlint
    # - funlen # works locally, but fails on github
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - noctx
    # - nolintlint
    - perfsprint
    # - revive # can't seem to quiet, and it breaks the build
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace

    # - cyclop
    # - depguard
    # - exhaustruct
    # - forbidigo
    # - forcetypeassert
    # - gochecknoglobals
    # - gochecknoinits
    # - interfacebloat
    # - ireturn
    # - nlreturn
    # - noinlineerr
    # - nonamedreturns
    # - paralleltest
    # - revive
    # - testpackage
    # - thelper
    # - varnamelen
    # - wrapcheck
    # - wsl
    # - wsl_v5

  settings:
    funlen:
      lines: 100
      statements: 50
    gocyclo:
      min-complexity: 15
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    revive:
      confidence: 0
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: EXC0001
    paths:
      - third_party$
      - builtin$
      - examples$
      # don't lint upstream code:
      - walk\.go$
      - walk_test\.go$
      - golang/golang_.*\.go$
      
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/rasa/compat
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      # don't lint upstream code:
      - walk\.go$
      - walk_test\.go$
      - golang/golang_.*\.go$
