# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - format_overrides:
      - goos: windows
        formats: ['zip']
dockers:
  - image_templates:
    - "ghcr.io/rasa/compat:latest"
    - "ghcr.io/rasa/compat:{{ .Major }}"
    - "ghcr.io/rasa/compat:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/rasa/compat:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    # OCI annotations: https://github.com/opencontainers/image-spec/blob/main/annotations.md
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
release:
  github:
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  disable: true
