---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: build-all-releases

on:
  workflow_call: # Required so this workflow can be called from another workflow
    inputs:
      verbose_testing:
        type: string
        default: "false"
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      # checkov:skip=CKV_GHA_7: The build output cannot be affected by user parameters...
      verbose_testing:
        description: "Test with -v options."
        type: choice
        options:
          - "false"
          - "true"
        default: "false"

permissions:
  contents: read

jobs:
  build-all-releases:
    name: build-all-releases
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-24.04 # ubuntu-latest
          - windows-2025
          - macos-15 # arm64
          - ubuntu-24.04-arm
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - windows-11-arm
          - windows-2022 # windows-latest
          - macos-15-large # amd64
          - macos-14 # arm64 # macos-latest
          - macos-14-large # amd64
          - macos-13 # amd64
          - macos-13-xlarge # arm64

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        # if: runner.os != 'Windows'
        with:
          go-version: '1.24'
          check-latest: true
          cache: false

      # Let's see if we see the same 80% speed improvement as mentioned in
      # https://github.com/elastic/apm-server/pull/15623#issuecomment-2648709041
      # failing on windows-11-arm:
      # - uses: antontroshin/setup-go@bda02de8887c9946189f81e7e59512914aeb9ea4
      #   if: runner.os == 'Windows'
      #   with:
      #     go-version: '1.24'
      #     check-latest: true
      #     cache: false

      - name: Set Go cache variables
        run: |
          printf '::notice ::%s\n' "$(go version)"
          # printf 'GOVERSION=%s\n'  "$(go version | sed 's#^.*go##;s# .*##')" >>"${GITHUB_ENV}"
          printf 'GOCACHE=%s\n'    "$(go env GOCACHE | tr '\\' '/')" >>"${GITHUB_ENV}"
          printf 'GOMODCACHE=%s\n' "$(go env GOMODCACHE | tr '\\' '/')" >>"${GITHUB_ENV}"
          go env

      - name: Cache Go's build and mod caches
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.GOCACHE }}
            ${{ env.GOMODCACHE }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          printf 'inputs.verbose_testing="%s"\n' "${{ inputs.verbose_testing }}"
          TEST_OPTS=()
          if [[ "${{ inputs.verbose_testing }}" == "true" ]]; then
            TEST_OPTS+=(-v)
          fi
          export TEST_OPTS="${TEST_OPTS[*]}"
          printf 'TEST_OPTS="%s"\n' "${TEST_OPTS}"
          make ci 
        env:
          COMPAT_DEBUG: 1
