---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: build-most

"on":
  workflow_call:
  workflow_dispatch:

jobs:
  build-matrix:
    uses: ./.github/workflows/build-matrix.yml
    with:
      runner: top6
    secrets: inherit
  build-nocgo:
    uses: ./.github/workflows/build-nocgo.yml
    with:
      goarches: all
    secrets: inherit
    # if: success()
    # needs: build-matrix
  build-android:
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
    # if: success()
    # needs: build-nocgo
  build-ios:
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit
    # if: success()
    # needs: build-android

permissions:
  contents: read
