name: build-all

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      runner: all
    secrets: inherit
  build-only-nocgo:
    uses: ./.github/workflows/build-only-nocgo.yml
    with:
      goarches: all
    needs: build
    if: success()
    secrets: inherit
  build-only-android:
    uses: ./.github/workflows/build-only-android.yml
    needs: build-only-nocgo
    if: success()
    secrets: inherit
  build-only-ios:
    uses: ./.github/workflows/build-only-ios.yml
    needs: build-only-android
    if: success()
    secrets: inherit
