---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: build

on: # yamllint disable-line rule:truthy
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      # - '.github/workflows/*'
      # - '.goreleaser.yml'
      # - 'Makefile'
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      # - '.github/workflows/*'
      # - '.goreleaser.yml'
  workflow_call:
    inputs:
      compat_debug:
        default: ACLS
        type: string
      compat_debug_fs:
        default: All
        type: string
      enabled:
        default: 'yes'
        type: string
      make_cmd:
        default: bldtest
        type: string
      runner:
        default: ubuntu-24.04
        type: string
      sudo:
        default: 'yes'
        type: string
      test_opts:
        default: '-v'
        type: string
    secrets:
      CODECOV_TOKEN:
        required: false

  workflow_dispatch:
    inputs:
      compat_debug:
        description: 'COMPAT_DEBUG environment variable'
        default: ACLS
        type: string
      compat_debug_fs:
        description: 'COMPAT_DEBUG_FS environment variable'
        default: All
        type: string
      enabled:
        description: 'Run action'
        default: yes
        type: choice
        options:
          - 'yes'
      make_cmd:
        description: 'Make command'
        default: bldtest
        type: string
      runner:
        description: 'GitHub runner to use'
        default: ubuntu-24.04
        type: choice
        options:
          - ubuntu-26.04
          - windows-2025 # windows-latest
          - macos-26 # arm64 # macos-latest
          - ---previous-releases---
          - ubuntu-24.04 # ubuntu-latest
          - ubuntu-22.04
          - macos-15 # arm64
          - windows-2022
          - ---arm-variations---
          - ubuntu-26.04-arm
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - windows-11-arm
          - macos-26-xlarge # arm64
          - ---amd-variations---
          - macos-26-large # amd64
          - macos-26-intel # amd64
          - macos-15-large # amd64
          - ---older-releases---
          - macos-14 # arm64
          - macos-14-large # amd64
      sudo:
        description: 'Run tests under sudo'
        type: choice
        options:
          - yes
          - no
      test_opts:
        description: 'Test options (eg: -v -run TestX -short -tags debug)'
        default: '-v'
        type: string

env:
  COMPAT_DEBUG: ${{ inputs.compat_debug || 'ACLS' }}
  COMPAT_DEBUG_FS: ${{ inputs.compat_debug_fs || 'All' }}
  ENABLED: >-
    ${{
      inputs.enabled == true ||
      inputs.enabled == 'yes' ||
      github.event_name == 'push' ||
      github.event_name == 'pull_request'
    }}
  MAKE_CMD: ${{ inputs.make_cmd || 'bldtest' }}
  RUNNER: ${{ inputs.runner || 'ubuntu-24.04' }}
  SUDO: >-
    ${{
      inputs.sudo == 'yes' ||
      inputs.sudo == true ||
      github.event_name == 'push' ||
      github.event_name == 'pull_request'
    }}
  TEST_OPTS: ${{ inputs.test_opts || '' }}

jobs:
  build:
    name: build
    if: >-
      inputs.enabled == 'yes' ||
      inputs.enabled == true ||
      github.event_name == 'push' ||
      github.event_name == 'pull_request'
    runs-on: ${{ inputs.runner || 'ubuntu-24.04' }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
          show-progress: false

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - run: printf '::notice ::%s\n' "$(go version)"

      # is this really needed?
      # if [[ "${{ runner.os }}" == "Windows" ]]; then
        # use 'env PATH=$PATH' prefix instead:
        # --preserve-env=PATH,COMPAT_DEBUG,COMPAT_DEBUG_FS,TEST_OPTS

      - name: Set environment variables
        run: |
          if [[ "${SUDO}" == "true" ]]; then
            if builtin command -v sudo &>/dev/null; then
              sudo='sudo -E -n'
            fi
          fi
          printf "GOCACHE=%s\n" "$(go env GOCACHE)" | tr '\\' '/' >>"${GITHUB_ENV}"
          printf "GOMODCACHE=%s\n" "$(go env GOMODCACHE)" | tr '\\' '/' >>"${GITHUB_ENV}"
          printf "GOVERSION=%s\n" "$(go version | sed 's|^.*go||; s| .*||;')" >>"${GITHUB_ENV}"
          printf "sudo=%s\n" "${sudo}" >>"${GITHUB_ENV}"
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            printf 'UMASK=022\n' >>"${GITHUB_ENV}"
          fi
          cat "${GITHUB_ENV}"

      - name: Show environment variables
        run: |
          printf 'COMPAT_DEBUG   ="%s"\n' "${COMPAT_DEBUG}"
          printf 'COMPAT_DEBUG_FS="%s"\n' "${COMPAT_DEBUG_FS}"
          printf 'ENABLED        ="%s"\n' "${ENABLED}"
          printf 'GOCACHE        ="%s"\n' "${GOCACHE}"
          printf 'GOMODCACHE     ="%s"\n' "${GOMODCACHE}"
          printf 'GOVERSION      ="%s"\n' "${GOVERSION}"
          printf 'PATH           ="%s"\n' "${PATH}"
          printf 'sudo           ="%s"\n' "${sudo}"
          printf 'SUDO           ="%s"\n' "${SUDO}"
          printf 'TEST_OPTS      ="%s"\n' "${TEST_OPTS}"
          printf 'UMASK          ="%s"\n' "${UMASK}"

      - name: make ${{ env.MAKE_CMD }}
        run: >-
          ${sudo} 
          env "PATH=${PATH}"
          make "${MAKE_CMD}" TEST_OPTS="${TEST_OPTS}"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: false
          files: ./coverage.out
          name: coverage-${{ runner.os }}
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage
        if: env.ACT != 'true'
        uses: actions/upload-artifact@v7
        with:
          name: coverage-${{ runner.os }}
          path: coverage.*

      - name: chown ./dist
        run: |
          set -vx
          test -d ./dist -a -n "${sudo}" || exit 0
          ${sudo} chown -R "$(id -un)":"$(id -gn)" ./dist "${GOCACHE}" "${GOMODCACHE}"
          ls -ld ./dist
          ls -lR ./dist

      - name: go tool goreleaser release --clean --snapshot
        if: contains(fromJSON('["all", "build", "ci", "precommit"]'), inputs.make_cmd) && runner.os == 'Linux'
        run: |
          if [[ -f go.tool.mod ]]; then
            export GOFLAGS="${GOFLAGS} -modfile=go.tool.mod"
          fi
          go tool goreleaser release --clean --snapshot

      - name: Upload dist
        if: contains(fromJSON('["all", "build", "ci", "precommit"]'), inputs.make_cmd) && env.ACT != 'true'
        uses: actions/upload-artifact@v7
        with:
          name: dist-${{ inputs.runner }}
          path: dist

permissions:
  contents: read
