name: build-only-windows

on:
  workflow_call: # Required so this workflow can be called from another workflow
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-only-windows:
    uses: ./.github/workflows/build.yml
    # name: build-only-windows
    with:
      runner: windows-2025
    secrets: inherit
