name: build-ubuntu

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      # - '.github/workflows/*'
      # - '.goreleaser.yml'
      # - 'Makefile'
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      # - '.github/workflows/*'
      # - '.goreleaser.yml'
  workflow_call: # Required so this workflow can be called from another workflow
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-ubuntu:
    uses: ./.github/workflows/build.yml
    name: build-ubuntu
    with:
      runner: ubuntu-24.04
    secrets: inherit
