name: build-all

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      runner: all
    secrets: inherit
  build-most:
    uses: ./.github/workflows/build-most.yml
    needs: build
    with:
      cpu: all
    if: success()
    secrets: inherit
  build-android:
    uses: ./.github/workflows/build-android.yml
    needs: build-most
    if: success()
    secrets: inherit
  build-ios:
    uses: ./.github/workflows/build-ios.yml
    needs: build-android
    if: success()
    secrets: inherit
