name: build-all

on:
  workflow_call:
  workflow_dispatch:

# mega-linter needs:
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  build-most:
    uses: ./.github/workflows/build-most.yml
    secrets: inherit
  build-android:
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
  build-ios:
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit
