name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        if: runner.os != 'Windows'
        with:
          go-version: '1.24'
          check-latest: true
          cache: false

      # Let's see if we see the same 80% speed improvement as mentioned in
      # https://github.com/elastic/apm-server/pull/15623#issuecomment-2648709041
      - uses: antontroshin/setup-go@bda02de8887c9946189f81e7e59512914aeb9ea4
        if: runner.os == 'Windows'
        with:
          go-version: '1.24'
          check-latest: true
          cache: false

      - name: run go version
        run: |
          printf '::notice ::%s\n' "$(go version)"
          echo "GO_VERSION=$(go version | sed 's#^.*go##;s# .*##')" >>"${GITHUB_ENV}"
          go env

      - uses: actions/cache/restore@v4
        with:
          enableCrossOsArchive: true
          path: |
            ~/go/pkg/mod/cache
            ~/.cache/go-build
          key: go-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-
            
      # - uses: actions/cache@v4
      #  with:
      #    path: |
      #      ~/.cache/go-build
      #      ~/go/pkg/mod'
      #      C:/Users/runneradmin/AppData/Local/go-build
      #      C:/Users/runneradmin/go/pkg/mod
      #      C:\\Users\\runneradmin\\AppData\\Local\\go-build
      #      C:\\Users\\runneradmin\\go\\pkg\\mod
      #    key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-package-${{ hashFiles('**/go.sum') }}

      - name: Build
        run: make ci
      - name: Upload coverage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-${{ matrix.os }}
          path: coverage.*

      - run: go tool goreleaser release --clean --snapshot
        if: ${{ runner.os == 'Linux' }}

      - name: Upload dist
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: dist-${{ matrix.os }}
          path: dist

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          fail_ci_if_error: false
          files: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
