name: pre-release

on:
  workflow_call:
  workflow_dispatch:

# mega-linter needs:
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  mega-linter:
    uses: ./.github/workflows/mega-linter.yml
    secrets: inherit
  build-most:
    uses: ./.github/workflows/build-most.yml
    if: success()
    needs: mega-linter
    secrets: inherit
  test-all:
    uses: ./.github/workflows/test-all.yml
    if: success()
    needs: build-most
    secrets: inherit
