name: pre-release

on:
  workflow_dispatch:

# mega-linter requies:
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  mega-linter:
    uses: ./.github/workflows/mega-linter.yml
    secrets: inherit
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  build-all:
    uses: ./.github/workflows/build-all.yml
    secrets: inherit
  build-android:
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
  build-ios:
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit
  test-dragonflybsd:
    uses: ./.github/workflows/test-dragonflybsd.yml
    secrets: inherit
  test-freebsd:
    uses: ./.github/workflows/test-freebsd.yml
    secrets: inherit
  test-illumos:
    uses: ./.github/workflows/test-illumos.yml
    secrets: inherit
  test-netbsd:
    uses: ./.github/workflows/test-netbsd.yml
    secrets: inherit
  test-openbsd:
    uses: ./.github/workflows/test-openbsd.yml
    secrets: inherit
  test-solaris:
    uses: ./.github/workflows/test-solaris.yml
    secrets: inherit
  test-wasm:
    uses: ./.github/workflows/test-wasm.yml
    secrets: inherit
