name: pre-release

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# mega-linter needs:
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  mega-linter:
    uses: ./.github/workflows/mega-linter.yml
    secrets: inherit
  build-all:
    uses: ./.github/workflows/build-all.yml
    secrets: inherit
  test-all:
    uses: ./.github/workflows/test-all.yml
    secrets: inherit
  build-all-releases:
    uses: ./.github/workflows/build-all-releases.yml
    secrets: inherit
