
name: test-freebsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-freebsd:
    name: test-freebsd
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    # continue-on-error: true
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/freebsd-vm@v1
      with:
        # release: "15.0"
        # arch: aarch64
        # envs: 'GITHUB_TOKEN'
        usesh: true
        copyback: false
        prepare: |
          pkg update -f
          pkg install -y go
        run: |
          go version
          rv=0
          if go build -trimpath ./...; then
            printf '::notice ::build succeeded: %s\n' "$(go version)"
          else
            rv=$?
            printf '::error ::build failed: %s (error %s)\n' "$(go version)" "${rv}"
          fi
          if go test -v .; then
            printf '::notice ::tests succeeded: %s\n' "$(go version)"
          else
            rv=$?
            printf '::error ::tests failed: %s (error %s)\n' "$(go version)" "${rv}"
          fi
          exit "${rv}"
