---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: test-all-bsds

"on":
  workflow_call:
    inputs:
      GOOPTS:
        type: string
        default: ''
  workflow_dispatch:
    inputs:
      GOOPTS:
        type: string
        default: ''
        description: 'Build/test options (eg: -tags fstat)'

jobs:
  test-dragonflybsd:
    uses: ./.github/workflows/test-dragonflybsd.yml
    with:
      GOOPTS: ${{ inputs.GOOPTS }}
    secrets: inherit
  test-freebsd:
    uses: ./.github/workflows/test-freebsd.yml
    with:
      GOOPTS: ${{ inputs.GOOPTS }}
    secrets: inherit
    # if: success()
    # needs: test-dragonflybsd
  test-netbsd:
    uses: ./.github/workflows/test-netbsd.yml
    with:
      GOOPTS: ${{ inputs.GOOPTS }}
    secrets: inherit
    # if: success()
    # needs: test-freebsd
  test-openbsd:
    uses: ./.github/workflows/test-openbsd.yml
    with:
      GOOPTS: ${{ inputs.GOOPTS }}
    secrets: inherit
    # if: success()
    # needs: test-netbsd

permissions:
  contents: read
