
name: test-freebsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-freebsd:
    name: test-freebsd
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/freebsd-vm@v1
      with:
        # release: "15.0"
        # arch: aarch64
        # envs: 'GITHUB_TOKEN'
        usesh: true
        prepare: |
          pkg update -f
          pkg install -y go
        run: |
          printf '::notice ::%s\n' "$(go version)"
          go env
          if !.go build ./...; then
            printf "::error ::go build failed: error %s\n" "$?"
            exit 1
          fi
          if ! go test -v; then
            printf '::error ::go test failed: error %s\n" "$?"
            exit 1
          fi
