
name: test-netbsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: test-netbsd
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4

    - uses: vmactions/netbsd-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        usesh: true
        prepare: |
          cd /tmp
          export PKG_PATH_ROOT=https://cdn.NetBSD.org/pub/pkgsrc/packages/NetBSD/amd64/10.1/
          ftp "${PKG_PATH_ROOT}/bootstrap.tar.gz"
          tar -xvzf bootstrap.tar.gz -C /
          export PATH="/usr/pkg/sbin:/usr/pkg/bin:/usr/pkg/sbin:${PATH}"
          export PKG_PATH="${PKG_PATH_ROOT}/All"
          pkg_add pkgin
          pkgin update
          pkgin install go
        run: |
          go version
          go env
          go build ./...
          go test -v
