
name: test-openbsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-openbsd:
    name: test-openbsd
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/openbsd-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        usesh: true
        prepare: |
          pkg_add go
        run: |
          go version
          rv=0
          if go build -trimpath ./...; then
            echo "::notice ::build succeeded"
          else
            rv=$?
            printf '::error ::build failed: error %s\n" "${rv}"
          fi
          if go test -v .; then
            echo "::notice ::tests succeeded"
          else
            rv=$?
            printf '::error ::tests failed: error %s\n" "${rv}"
          fi
          exit "${rv}"
