
name: test-illumos

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  GO_VERSION: "1.24"

jobs:
  test-illumos:
    name: test-illumos (go 1.24)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/omnios-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        usesh: true
        copyback: false
        prepare: |
          GO_VERSION="${{ env.GO_VERSION }}"
          pkg_version="${GO_VERSION//.}"
          pkg install "go-${pkg_version}"
        run: |
          GO_VERSION="${{ env.GO_VERSION }}"
          PATH="/opt/ooce/go-${GO_VERSION}/bin:${PATH}"
          export PATH

          go version
          rv=0
          if go build -trimpath ./...; then
            printf '::notice ::build succeeded: %s\n' "$(go version)"
          else
            rv=$?
            printf '::error ::build failed: %s (error %s)\n' "$(go version)" "${rv}"
          fi
          if go test -v .; then
            printf '::notice ::tests succeeded: %s\n' "$(go version)"
          else
            rv=$?
            printf '::error ::tests failed: %s (error %s)\n' "$(go version)" "${rv}"
          fi
          exit "${rv}"
