name: test-all-solaris

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# mega-linter needs:
permissions:
  contents: read

jobs:
  test-illumos:
    uses: ./.github/workflows/test-illumos.yml
    secrets: inherit
  test-solaris:
    uses: ./.github/workflows/test-solaris.yml
    needs: test-illumos
    if: success()
    secrets: inherit
