name: test-all-wasms

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-js:
    uses: ./.github/workflows/test-js.yml
    secrets: inherit
  test-wasip1:
    uses: ./.github/workflows/test-wasip1.yml
    needs: test-js
    if: success()
    secrets: inherit
