name: test-js

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-js:
    name: test-js
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: |
        # Run Go js/wasm test in node.js
        printf '::notice ::%s\n' "$(go version)"
        GOROOT=$(go env GOROOT)
        cp "${GOROOT}/lib/wasm/wasm_exec.js" .
        GOOS=js GOARCH=wasm go test -v -exec="${GOROOT}/lib/wasm/go_js_wasm_exec" .
        node run-test.js
        exit 0
