
name: test-freebsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-freebsd:
    name: test-freebsd
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      GOOS: "freebsd"
      GOARCH: "amd64"
      # GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    # continue-on-error: true
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/freebsd-vm@v1
      with:
        # release: "15.0"
        # arch: aarch64
        # envs: 'GITHUB_TOKEN'
        usesh: true
        copyback: false
        prepare: |
          pkg update -f
          pkg install -y go
          pkg install -ycurl gtar jq || true
        # /sbin/sha256sum
        run: |
          # echo "PATH="
          # echo "${PATH}" | tr ':' '\n'
          # which curl gtar gsha256sum jq sha256sum tar || true

          go version
          go env

          rv=0
          if go build -trimpath ./...; then
            printf '::notice ::build succeeded: %s\n' "$(go version)"
          else
            rv=$?
            printf '::error ::build failed: %s (error %s)\n' "$(go version)" "${rv}"
          fi
          if go test -v .; then
            printf '::notice ::tests succeeded: %s\n' "$(go version)"
          else
            rv=$?
            printf '::error ::tests failed: %s (error %s)\n' "$(go version)" "${rv}"
          fi
          exit "${rv}"
