
name: test-solaris

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-solaris:
    name: test-solaris
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      GOOS: "solaris"
      GOARCH: "amd64"
      # GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    # continue-on-error: true
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/solaris-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        usesh: true
        copyback: false
        prepare: |
          pkg refresh --full
          pkg install --accept developer/go
          pkg install --accept coreutils web/curl archiver/gnu-tar text/jq || true
        run: |
          which curl gtar gsha256sum jq sha256sum tar || true

          go version
          go env

          rv=0
          if go build -trimpath ./...; then
            printf '::notice ::build succeeded: %s\n' "$(go version)"
          else
            rv=$?
            printf '::error ::build failed: %s (error %s)\n' "$(go version)" "${rv}"
          fi
          if go test -v .; then
            printf '::notice ::tests succeeded: %s\n' "$(go version)"
          else
            rv=$?
            printf '::error ::tests failed: %s (error %s)\n' "$(go version)" "${rv}"
          fi
          exit "${rv}"
