---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: test-no-cover

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-android:
    uses: ./.github/workflows/test-android.yml
    secrets: inherit
  test-tinygo:
    uses: ./.github/workflows/test-tinygo.yml
    needs: test-android
    secrets: inherit
