
name: test-openbsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-openbsd:
    name: test-openbsd
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    env:
      GOOS: openbsd
      GOARCH: amd64
      # GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    # continue-on-error: true
    steps:
    - uses: actions/checkout@v5
      with:
        show-progress: false

    - uses: vmactions/openbsd-vm@v1
      with:
        envs: 'GOOS GOARCH' # GITHUB_TOKEN'
        usesh: true
        copyback: false
        prepare: |
          # the double dashes are needed to avoid "ambiguous" warning.
          pkg_add coreutils curl gtar-- jq
          cd /usr/local/bin && ln -sf gsha256sum sha256sum
          # pkg_add go
        run: |
          ./download-build-test.sh
