---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: test-all

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-cover:
    uses: ./.github/workflows/test-cover.yml
    secrets: inherit
  test-no-cover:
    uses: ./.github/workflows/test-no-cover.yml
    needs: test-cover
    secrets: inherit
