---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: test-all-wasms

"on":
  workflow_call:
  workflow_dispatch:

jobs:
  test-js:
    uses: ./.github/workflows/test-js.yml
    secrets: inherit
  test-wasi:
    uses: ./.github/workflows/test-wasi.yml
    secrets: inherit
    # if: success()
    # needs: test-js

permissions:
  contents: read
