name: test-illumos

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-illumos:
    name: test-illumos
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    # continue-on-error: true
    env:
      GOOS: illumos
      GOARCH: amd64
      # GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v5
      with:
        show-progress: false

    - uses: vmactions/omnios-vm@v1
      with:
        envs: 'GOOS GOARCH' # GITHUB_TOKEN
        usesh: true
        copyback: false
        prepare: |
          pkg install web/curl archiver/gnu-tar util/jq
          # add developer/gcc14 for CGO
        run: |
          ./download-build-test.sh