
name: test-netbsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: test-netbsd
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4

    - uses: vmactions/netbsd-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        usesh: true
        # See https://go.dev/doc/install
        prepare: |
          rm -rf /usr/local/go
          curl -fsSL https://go.dev/dl/go1.24.3.netbsd-amd64.tar.gz -o go1.24.3.netbsd-amd64.tar.gz
          tar -C /usr/local -xzf go1.24.3.netbsd-amd64.tar.gz
          rm go1.24.3.netbsd-amd64.tar.gz

        run: |
          export PATH="${PATH}:/usr/local/go/bin"
          go version
          go env
          go build ./...
          go test -v
