name: test-all

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-tinygo:
    uses: ./.github/workflows/test-tinygo.yml
    secrets: inherit
  test-all-bsds:
    uses: ./.github/workflows/test-all-bsds.yml
    needs: test-tinygo
    if: success()
    secrets: inherit
  test-all-solaris:
    uses: ./.github/workflows/test-all-solaris.yml
    needs: test-all-bsds
    if: success()
    secrets: inherit
  test-all-wasms:
    uses: ./.github/workflows/test-all-wasms.yml
    needs: test-all-solaris
    if: success()
    secrets: inherit
  
