name: test-all-vms

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-all-bsds:
    uses: ./.github/workflows/test-all-bsds.yml
    secrets: inherit
  test-all-solaria:
    uses: ./.github/workflows/test-all-solaria.yml
    # needs: test-all-bsds
    # if: success()
    secrets: inherit
