---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: test-all

"on":
  workflow_call:
  workflow_dispatch:

jobs:
  test-top3:
    uses: ./.github/workflows/build-matrix.yml
    with:
      runner: top3
      make_cmd: test
    secrets: inherit
  test-android:
    uses: ./.github/workflows/test-android.yml
    secrets: inherit
    # if: success()
    # needs: test-top3
  test-ios:
    uses: ./.github/workflows/test-ios.yml
    secrets: inherit
    # if: success()
    # needs: test-android
  test-plan9:
    uses: ./.github/workflows/test-plan9.yml
    secrets: inherit
    # if: success()
    # needs: test-ios
  test-tiny:
    uses: ./.github/workflows/test-tiny.yml
    secrets: inherit
    # if: success()
    # needs: test-plan9
  test-all-wasms:
    uses: ./.github/workflows/test-all-wasms.yml
    secrets: inherit
    # if: success()
    # needs: test-tiny
  test-all-vms:
    uses: ./.github/workflows/test-all-vms.yml
    secrets: inherit
    # if: success()
    # needs: test-all-wasms

permissions:
  contents: read
