
name: test-freebsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-freebsd:
    name: test-freebsd
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/freebsd-vm@v1
      with:
        # release: "15.0"
        # arch: aarch64
        # envs: 'GITHUB_TOKEN'
        usesh: true
        prepare: |
          pkg update -f
          pkg install -y go
        run: |
          go version
          rv=0
          if go build -trimpath ./...; then
            echo '::notice ::build succeeded'
          else
            rv=$?
            printf '::error ::build failed: error %s\n' "${rv}"
          fi
          if go test -v .; then
            echo '::notice ::tests succeeded'
          else
            rv=$?
            printf '::error ::tests failed: error %s\n' "${rv}"
          fi
          exit "${rv}"
