
name: test-dragonflybsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-dragonflybsd:
    name: test-dragonflybsd
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/dragonflybsd-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        usesh: true
        prepare: |
          pkg update -f
          pkg install -y go
        run: |
          printf '::notice ::%s\n' "$(go version)"
          go env
          go build ./...
          go test -v
