---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: test-freebsd

"on":
  workflow_call:
    inputs:
      GOOPTS:
        type: string
        default: ''
  workflow_dispatch:
    inputs:
      GOOPTS:
        type: string
        default: ''
        description: 'Build/test options (eg: -tags fstat)'

env:
  CODECOV_SLUG: ${{ github.repository }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  GOOS: freebsd
  GOARCH: amd64
  GOOPTS: ${{ inputs.GOOPTS }}

jobs:
  test-freebsd:
    name: test-freebsd
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # continue-on-error: true
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
          show-progress: false

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync
    
      - uses: vmactions/freebsd-vm@v1
        with:
          envs: 'GOOS GOARCH GOOPTS CODECOV_SLUG CODECOV_TOKEN' # GITHUB_TOKEN'
          prepare: |
            pkg update -f
            pkg install -y bash curl git gzip gtar jq
            # pkg install -y go
          run: |
            ./download-build-test.sh
          sync: scp
          usesh: true
          # arch: aarch64
          # copyback: false
          # release: '15.0'

      - uses: codecov/codecov-action@v7
        with:
          files: ./coverage.out
          name: coverage-${{ env.GOOS }}
          token: ${{ secrets.CODECOV_TOKEN }}
          # fail_ci_if_error: false

permissions:
  contents: read
