
name: test-netbsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-netbsd:
    name: test-netbsd
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/netbsd-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        # usesh: true
        # See https://github.com/fsnotify/fsnotify/blob/main/.github/workflows/test.yml
        prepare: |
          export PATH="/usr/pkg/bin:${PATH}"
          attempts=9
          delay=1
          i=1
          while [ "${i}" -le "${attempts}" ]; do
            pkg_add go && break
            echo "Attempt ${i} failed. Retrying in ${delay} seconds..."
            sleep "${delay}"
            delay=$(expr "${delay}" \* 2)
            i=$(expr "${i}" + 1)
          done

        run: |
            export PATH="/usr/pkg/bin:${PATH}"
            (cd /usr/pkg/bin ; ln -sf go??? go)
            # printf '::notice ::%s\n' "$(go version)"
            go env
            if go build ./...; then
              echo "::notice ::build succeeded"
            else
              echo "::error ::build failed"
            fi
            if go test -v ./...; then
              echo "::notice ::tests succeeded"
            else
              echo '::error ::tests failed"
              exit 1
            fi
