
name: test-openbsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-openbsd:
    name: test-openbsd
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      GOOS: "openbsd"
      GOARCH: "amd64"
      # GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    # continue-on-error: true
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/openbsd-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        usesh: true
        copyback: false
        prepare: |
          pkg_add go
          pkg_add curl jq gtar- || true
        run: |
          which curl
          which jq
          which gtar
          which sha256sum

          go version
          go env

          rv=0
          if go build -trimpath ./...; then
            printf '::notice ::build succeeded: %s\n' "$(go version)"
          else
            rv=$?
            printf '::error ::build failed: %s (error %s)\n' "$(go version)" "${rv}"
          fi
          if go test -v .; then
            printf '::notice ::tests succeeded: %s\n' "$(go version)"
          else
            rv=$?
            printf '::error ::tests failed: %s (error %s)\n' "$(go version)" "${rv}"
          fi
          exit "${rv}"
