
name: test-netbsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-netbsd:
    name: test-netbsd
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    env:
      GOOS: netbsd
      GOARCH: amd64
      # GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    # continue-on-error: true
    steps:
    - uses: actions/checkout@v5
      with:
        show-progress: false

    - uses: vmactions/netbsd-vm@v1
      with:
        envs: 'GOOS GOARCH' # GITHUB_TOKEN'
        usesh: true
        copyback: false
        # See https://github.com/fsnotify/fsnotify/blob/main/.github/workflows/test.yml
        prepare: |
          echo 'PATH='
          echo "${PATH}" | tr ':' '\n'
          export PATH="/usr/sbin:${PATH}"
          pkg_add coreutils curl gtar jq
          cd /usr/pkg/bin && ln -sf gsha256sum sha256sum 
          # pkg_add go
        run: |
          ./download-build-test.sh

          # (cd /usr/pkg/bin ; ln -sf go??? go)
          # ls -l /usr/pkg/bin
