---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: test-solaris

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      GOOPTS:
        type: string
        default: ''
        description: "Options to pass to go command"
  workflow_dispatch:
    inputs:
      GOOPTS:
        type: string
        default: ''
        description: "Options to pass to go command"

env:
  CODECOV_SLUG: ${{ github.repository }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  GOOS: solaris
  GOARCH: amd64
  GOOPTS: ${{ inputs.GOOPTS }}

jobs:
  test-solaris:
    name: test-solaris
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # continue-on-error: true
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
          show-progress: false

      - uses: vmactions/solaris-vm@v1
        with:
          envs: 'GOOS GOARCH GOOPTS CODECOV_SLUG CODECOV_TOKEN' # GITHUB_TOKEN'
          usesh: true
          sync: scp
          prepare: |
            set +e
            # ignore error 4, which is returned when there's nothing to do
            # See https://github.com/vmactions/solaris-builder/blob/cda522c7/hooks/postBuild.sh#L55
            pkg refresh --full
            pkg install --accept shell/bash || true
            pkg install --accept web/curl || true
            pkg install --accept developer/versioning/git || true
            pkg install --accept archiver/gnu-tar || true
            pkg install --accept compress/gzip || true
            pkg install --accept text/jq || true
            # pkg install --accept developer/go || true
          run: |
            ./download-build-test.sh
          # copyback: false

      - uses: codecov/codecov-action@v7
        with:
          files: ./coverage.out
          name: coverage-${{ env.GOOS }}
          token: ${{ secrets.CODECOV_TOKEN }}
          # fail_ci_if_error: false

permissions:
  contents: read
