name: test-all-bsds

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-dragonflybsd:
    uses: ./.github/workflows/test-dragonflybsd.yml
    secrets: inherit
  test-freebsd:
    uses: ./.github/workflows/test-freebsd.yml
    needs: test-dragonflybsd
    # if: success()
    secrets: inherit
  test-netbsd:
    uses: ./.github/workflows/test-netbsd.yml
    needs: test-freebsd
    # if: success()
    secrets: inherit
  test-openbsd:
    uses: ./.github/workflows/test-openbsd.yml
    needs: test-netbsd
    # if: success()
    secrets: inherit
