name: test-tinygo

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  # See https://github.com/webassembly/binaryen/releases
  binaryen_version: "131"

jobs:
  test-tinygo:
    name: test-tinygo
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        go-version:
          - big: "1.26"
            # https://github.com/tinygo-org/tinygo/releases
            tiny: "0.41.1"
          # - big: "1.25"
          #  tiny: "0.39.0"

    env:
      GODEBUG: toolchaintrace=1
      GOTOOLCHAIN: local

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version.big }}

      - run: go mod download

      - uses: acifani/setup-tinygo@v3
        with:
          tinygo-version: "${{ matrix.go-version.tiny }}"
          binaryen-version: "${{ env.binaryen_version }}"

      - run: tinygo test -tags tinygo .

      - run: tinygo test -tags tinygo -covermode=atomic -coverprofile=coverage.out -coverpkg=. .
        continue-on-error: true
