name: test-illumos

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-illumos:
    name: test-illumos
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    # continue-on-error: true
    env:
      GOOS: illumos
      GOARCH: amd64
      CODECOV_SLUG: ${{ github.repository }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      # GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v7
      with:
        show-progress: false

    - uses: vmactions/omnios-vm@v1
      with:
        envs: 'GOOS GOARCH CODECOV_SLUG CODECOV_TOKEN' # GITHUB_TOKEN'
        usesh: true
        # copyback: false
        prepare: |
          pkg install shell/bash web/curl developer/versioning/git compress/gzip archiver/gnu-tar util/jq
          # add developer/gcc14 for CGO
        run: |
          ./download-build-test.sh

    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        fail_ci_if_error: false
        files: ./coverage.out
        name: coverage-${{ env.GOOS }}
        token: ${{ secrets.CODECOV_TOKEN }}
