name: test-wasip

# Inspired by:
# https://github.com/zonedb/zonedb/blob/main/.github/workflows/go.yaml
# MIT Licensed

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-wasip: # act fails if tag ends with a '1'
    name: test-wasip
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      # This is a special matrix that tests against the listed version AND the
      # Go version from go.mod. See usage in the actions/setup-go step.
      matrix:
        go-version:
          # - big: "1.23.11"
          #   tiny: "0.36.0"
          - big: "1.25"
            tiny: "0.39.0"
          - big: "1.24"
            tiny: "0.38.0"
        # FIXME: TinyGo needs to be manually bumped; it doesn't immediately
        # release support for new major Go versions something should ping when a
        # new version is available.
        # include:
        #   - go-version:
        #       file: "go.mod"
        #       tiny: "0.37.0"

    env:
      GODEBUG: toolchaintrace=1
      GOTOOLCHAIN: local

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{ matrix.go-version.big }} # overrides go-version-file when a value is present
          go-version-file: ${{ matrix.go-version.file }}
          check-latest: true

      - run: go mod download

      # - run: printf '::notice ::%s\n' "$(go version)"

      - run: |
          # Add wasm to PATH
          echo "$(go env GOROOT)/misc/wasm" >> "${GITHUB_PATH}"
          echo "$(go env GOROOT)/lib/wasm" >> "${GITHUB_PATH}"

      - run: which go_wasip1_wasm_exec

      - uses: acifani/setup-tinygo@v2.0.1
        with:
          tinygo-version: "${{ matrix.go-version.tiny }}"
          binaryen-version: "123"

      - run: wasm-opt --version

      - uses: bytecodealliance/actions/wasmtime/setup@v1.1.1
        with:
          version: v35.0.0

      # https://go.dev/blog/wasi#running-go-tests-with-wasip1
      - run: GOOS=wasip1 GOARCH=wasm go test -v .

      - run: tinygo test -target=wasip1 -tags tinygo -v .

      # - run: tinygo test -bench -target=wasip1 -tags tinygo -v ./
