
name: test-freebsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-freebsd:
    name: test-freebsd
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    env:
      GOOS: freebsd
      GOARCH: amd64
      # GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    # continue-on-error: true
    steps:
    - uses: actions/checkout@v5
      with:
        show-progress: false

    - uses: vmactions/freebsd-vm@v1
      with:
        # release: "15.0"
        # arch: aarch64
        envs: 'GOOS GOARCH' # GITHUB_TOKEN'
        usesh: true
        copyback: false
        prepare: |
          pkg update -f
          pkg install -y curl gtar jq
          # pkg install -y go
        run: |
          ./download-build-test.sh