
name: test-solaris

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-solaris:
    name: test-solaris
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/solaris-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        usesh: true
        prepare: |
          pkg refresh --full
          pkg install --accept --licenses developer/go
        run: |
          # printf '::notice ::%s\n' "$(go version)"
          go env
          if go build ./...; then
            echo "::notice ::build succeeded"
          else
            echo "::error ::build failed"
          fi
          if go test -v ./...; then
            echo "::notice ::tests succeeded"
          else
            echo '::error ::tests failed"
            exit 1
          fi
