
name: test-netbsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: test-netbsd
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4

    - uses: vmactions/netbsd-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        # usesh: true
        # See https://github.com/fsnotify/fsnotify/blob/main/.github/workflows/test.yml
        prepare: |
          pkg_add go
        run: |
            useradd -mG wheel action
            su action -c '/usr/pkg/bin/go??? version'
            su action -c '/usr/pkg/bin/go??? env'
            su action -c '/usr/pkg/bin/go??? build ./...'
            su action -c '/usr/pkg/bin/go??? test -v ./...'
