---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: test-tiny

"on":
  workflow_call:
  workflow_dispatch:

jobs:
  test-tiny:
    name: test-tiny
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
          show-progress: false

      - uses: actions/setup-go@v7
        with:
          go-version-file : go.mod
          check-latest: true
          cache: true

      - run: printf '::notice ::%s\n' "$(go version)"

      - run: go mod download

      - run: go test -covermode=atomic -coverprofile=coverage.out -coverpkg=. -tags tinygo -v ./...

      - uses: codecov/codecov-action@v7
        with:
          files: ./coverage.out
          name: coverage-tinygo
          token: ${{ secrets.CODECOV_TOKEN }}
          # fail_ci_if_error: false

permissions:
  contents: read
