
name: test-dragonflybsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-dragonflybsd:
    name: test-dragonflybsd
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      GOOS: "dragonfly"
      GOARCH: "amd64"
      # GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    # continue-on-error: true
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/dragonflybsd-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        usesh: true
        copyback: false
        prepare: |
          pkg update -f
          pkg install -y go
          pkg install -y curl jq gtar || true

        # NOTE: dragonflybsd requires -buildvcs=false
        run: |
          which curl
          which jq
          which gtar
          which sha256sum

          go version
          go env

          rv=0
          if go build -buildvcs=false -trimpath ./...; then
            printf '::notice ::build succeeded: %s\n' "$(go version)"
          else
            rv=$?
            printf '::error ::build failed: %s (error %s)\n' "$(go version)" "${rv}"
          fi
          if go test -v .; then
            printf '::notice ::tests succeeded: %s\n' "$(go version)"
          else
            rv=$?
            printf '::error ::tests failed: %s (error %s)\n' "$(go version)" "${rv}"
          fi
          exit "${rv}"

