name: test-all

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-all-bsds:
    uses: ./.github/workflows/test-all-bsds.yml
    secrets: inherit
  test-all-solaris:
    uses: ./.github/workflows/test-all-solaris.yml
    secrets: inherit
  test-all-wasms:
    uses: ./.github/workflows/test-all-wasms.yml
    secrets: inherit
