
name: test-dragonflybsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-dragonflybsd:
    name: test-dragonflybsd
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/dragonflybsd-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        usesh: true
        copyback: false
        prepare: |
          pkg update -f
          pkg install -y go
        run: |
          # NOTE: dragonflybsd requires -buildvcs=false
          go version
          rv=0
          if go build -buildvcs=false -trimpath ./...; then
            echo '::notice ::build succeeded'
          else
            rv=$?
            printf '::error ::build failed: error %s\n' "${rv}"
          fi
          if go test -v .; then
            echo '::notice ::tests succeeded'
          else
            rv=$?
            printf '::error ::tests failed: error %s\n' "${rv}"
          fi
          exit "${rv}"
