
name: test-netbsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-netbsd:
    name: test-netbsd
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/netbsd-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        usesh: true
        copyback: false
        # See https://github.com/fsnotify/fsnotify/blob/main/.github/workflows/test.yml
        prepare: |
          PATH="/usr/sbin:/usr/pkg/bin:/usr/pkg/sbin:${PATH}"
          export PATH
          if ! command -v pkg_add; then
            find / -name 'pkg_add' -type f 2>/dev/null
          fi
          attempts=4
          delay=1
          i=1
          while [ "${i}" -le "${attempts}" ]; do
            pkg_add go && break
            echo "Attempt ${i} failed. Retrying in ${delay} seconds..."
            sleep "${delay}"
            delay=$(expr "${delay}" \* 2)
            i=$(expr "${i}" + 1)
          done

        run: |
          PATH="/usr/pkg/bin:${PATH}"
          export PATH
          (cd /usr/pkg/bin ; ln -sf go??? go)

          go version
          rv=0
          if go build -trimpath ./...; then
            echo '::notice ::build succeeded'
          else
            rv=$?
            printf '::error ::build failed: error %s\n' "${rv}"
          fi
          if go test -v .; then
            echo '::notice ::tests succeeded'
          else
            rv=$?
            printf '::error ::tests failed: error %s\n' "${rv}"
          fi
          exit "${rv}"
