name: test-all

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-tinygo:
    uses: ./.github/workflows/test-tinygo.yml
    secrets: inherit
  test-all-wasms:
    uses: ./.github/workflows/test-all-wasms.yml
    needs: test-tinygo
    # if: success()
    secrets: inherit
  test-all-vms:
    uses: ./.github/workflows/test-all-vms.yml
    needs: test-all-wasms
    # if: success()
    secrets: inherit
