
name: test-openbsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: test-openbsd
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4

    - uses: vmactions/openbsd-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        usesh: true
        prepare: |
          pkg_add go
        run: |
          go version
          go env
          go build ./...
          go test -v
