---
# yaml-language-server: $schema https://json.schemastore.org/github-workflow.json

name: test-openbsd

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      GOOPTS:
        type: string
        default: ''
        description: "Options to pass to go command"
  workflow_dispatch:
    inputs:
      GOOPTS:
        type: string
        default: '-tags fstat'
        description: "Options to pass to go command"

env:
  CODECOV_SLUG: ${{ github.repository }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  GOOS: openbsd
  GOARCH: amd64
  GOOPTS: ${{ inputs.GOOPTS }}
jobs:
  test-openbsd:
    name: test-openbsd
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # continue-on-error: true
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
          show-progress: false

      - uses: vmactions/openbsd-vm@v1
        with:
          envs: 'GOOS GOARCH GOOPTS CODECOV_SLUG CODECOV_TOKEN' # GITHUB_TOKEN'
          usesh: true
          sync: scp
          # copyback: false
          prepare: |
            # the double dashes are needed to avoid "ambiguous" warning.
            pkg_add bash coreutils curl git gzip gtar-- jq
            cd /usr/local/bin && ln -sf gsha256sum sha256sum
            # pkg_add go
          run: |
            ./download-build-test.sh

      - uses: codecov/codecov-action@v7
        with:
          # fail_ci_if_error: false
          files: ./coverage.out
          name: coverage-${{ env.GOOS }}
          token: ${{ secrets.CODECOV_TOKEN }}

permissions:
  contents: read
