name: test-wasm

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: test-wasm
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: |
        # Run Go WASM test in Node.js
        go version
        go env
        cp "$(go env GOROOT)/lib/wasm/wasm_exec.js" . || wget https://raw.githubusercontent.com/golang/go/refs/heads/master/lib/wasm/wasm_exec.js
        GOOS=js GOARCH=wasm go test -c -o main.test.wasm .
        echo 'require("./wasm_exec.js"); const go = new Go(); WebAssembly.instantiate(fs.readFileSync("main.test.wasm"), go.importObject).then(r => go.run(r.instance));' > run-test.js
        node run-test.js
