
name: test-dragonflybsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-dragonflybsd:
    name: test-dragonflybsd
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    env:
      GOOS: dragonfly
      GOARCH: amd64
      # GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    # continue-on-error: true
    steps:
    - uses: actions/checkout@v5

    - uses: vmactions/dragonflybsd-vm@v1
      with:
        envs: 'GOOS GOARCH' # GITHUB_TOKEN'
        usesh: true
        copyback: false
        prepare: |
          pkg update -f
          pkg install -y coreutils curl gtar jq
          cd /usr/local/bin && ln -sf gsha256sum sha256sum
          # pkg install -y go
        run: |
          ./download-build-test.sh
