
name: test-netbsd

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: test-netbsd
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # env:
    #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4

    - uses: vmactions/netbsd-vm@v1
      with:
        # envs: 'GITHUB_TOKEN'
        # usesh: true
        # See https://github.com/fsnotify/fsnotify/blob/main/.github/workflows/test.yml
        prepare: |
          pkg_add go
        run: |
            PATH="/usr/pkg/bin:${PATH}"
            export PATH
            CWD=$(pwd)
            cd /usr/pkg/bin
            ln -sf go??? go
            cd "${CWD}"
            go version
            go env
            go build ./...
            go test -v ./...
